<?xml version="1.0" encoding="utf-8"?>
<!--
  PO_Canonical_to_X12_850_006030.xslt
  =============================================================================
  Authoritative source: docs/purchaser-workflow-epic-design.md §4.2, §4.3
  Target schema: infra/integration-account/schemas/X12_00603_850.xsd
                 (Microsoft's official X12 850, standards version 00603/006030,
                  supplied by the product owner — NOT hand-authored).

  PLACEMENT: app Artifacts/Maps (logicapps/purchaser/Artifacts/Maps). The
  built-in Transform XML action (step 5b) loads maps from the app project's
  Artifacts/Maps folder — no Integration Account needed for the transform.

  INPUT : canonical Purchase Order XML (no namespace) produced by xml(json(...))
          — governed by PurchaseOrder_Canonical.xsd.
  OUTPUT: X12 850 (006030) transaction-set XML matching the official schema
          above. The X12 Encode action (step 5c) serializes it into the flat
          X12 006030 interchange.

  NAMESPACE MODEL (reconciled against the official schema — important):
    The official schema is a BizTalk/Logic Apps EDI schema with
    elementFormDefault = UNQUALIFIED. Therefore:
      * GLOBAL elements — the root X12_00603_850, the segment elements reached by
        <xs:element ref="..."> (BEG, REF, DTM, N1, N3, N4, PO1, PID_2, CTT) and
        the loop wrappers (N1Loop1, PO1Loop1, PIDLoop1, CTTLoop1) — ARE in the
        target namespace (http://schemas.microsoft.com/BizTalk/EDI/X12/2006).
        They are emitted with the x12: prefix.
      * LOCAL elements — the inline ST and SE segments (declared inside the root
        complexType) and EVERY data-element field (ST01, BEG01, REF01, N101,
        N401, PO101, PID01, CTT01, SE01, ...) — are in NO namespace. They are
        emitted UNPREFIXED, and because no default namespace is declared anywhere
        in this stylesheet, they land in no namespace, exactly as required.
    The detail item description segment is the GLOBAL element **PID_2** (the
    heading-level PID is a different global element); the PO1 loop references
    PID_2, so the emitted tag is <x12:PID_2>.

  ENVELOPE / CONTROL NUMBERS: ISA/GS and ISA13/GS06/ST02 control numbers are
  generated by the X12 SEND AGREEMENT (§4.1). ST02/SE01/SE02 are emitted here as
  placeholders; X12 Encode overwrites SE01 with the real segment count and the
  agreement assigns the control numbers.

  §4.2 MAPPING IMPLEMENTED (unchanged from the design):
    BEG01=00 (original), BEG02=NE (new order), BEG03=poNumber,
    BEG05=orderDate reformatted YYYY-MM-DD -> CCYYMMDD (translate strips dashes).
    REF01=CO, REF02=buyer.id.
    DTM01=002, DTM02=requestedDeliveryDate (CCYYMMDD) — segment omitted if null.
    N1Loop1 ST: N101=ST, N102=shipTo.name; N3=line1(+line2); N4=city/state/zip/country.
    N1Loop1 BT: N101=BT, N102=billTo.name; N3/N4 = billTo.*.
    PO1Loop1 (1 per line): PO101=lineNumber, PO102=quantity, PO103=uom,
      PO104=unitPrice, PO106=BP, PO107=sku; PIDLoop1/PID_2: PID01=F, PID05=description.
    CTTLoop1/CTT: CTT01=count(lines), CTT02=sum(quantity) hash total.
  =============================================================================
-->
<xsl:stylesheet version="1.0"
                xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
                xmlns:x12="http://schemas.microsoft.com/BizTalk/EDI/X12/2006"
                exclude-result-prefixes="xsl">

  <xsl:output method="xml" version="1.0" encoding="utf-8" indent="yes"/>
  <xsl:strip-space elements="*"/>

  <xsl:template match="/">
    <xsl:apply-templates select="purchaseOrder"/>
  </xsl:template>

  <xsl:template match="purchaseOrder">
    <x12:X12_00603_850>

      <!-- ST — inline (local) segment => NO namespace. ST02 placeholder. -->
      <ST>
        <ST01>850</ST01>
        <ST02>0001</ST02>
      </ST>

      <!-- BEG — global segment => x12 namespace; fields => no namespace -->
      <x12:BEG>
        <BEG01>00</BEG01>
        <BEG02>NE</BEG02>
        <BEG03><xsl:value-of select="poNumber"/></BEG03>
        <BEG05><xsl:value-of select="translate(orderDate, '-', '')"/></BEG05>
      </x12:BEG>

      <!-- REF — customer/buyer reference (CO) -->
      <x12:REF>
        <REF01>CO</REF01>
        <REF02><xsl:value-of select="buyer/id"/></REF02>
      </x12:REF>

      <!-- DTM — requested delivery date (002). Omit if not supplied. -->
      <xsl:if test="requestedDeliveryDate and normalize-space(requestedDeliveryDate) != ''">
        <x12:DTM>
          <DTM01>002</DTM01>
          <DTM02><xsl:value-of select="translate(requestedDeliveryDate, '-', '')"/></DTM02>
        </x12:DTM>
      </xsl:if>

      <!-- N1Loop1 — Ship To (ST) -->
      <x12:N1Loop1>
        <x12:N1>
          <N101>ST</N101>
          <N102><xsl:value-of select="shipTo/name"/></N102>
        </x12:N1>
        <x12:N3>
          <N301><xsl:value-of select="shipTo/line1"/></N301>
          <xsl:if test="shipTo/line2 and normalize-space(shipTo/line2) != ''">
            <N302><xsl:value-of select="shipTo/line2"/></N302>
          </xsl:if>
        </x12:N3>
        <x12:N4>
          <N401><xsl:value-of select="shipTo/city"/></N401>
          <N402><xsl:value-of select="shipTo/state"/></N402>
          <N403><xsl:value-of select="shipTo/postalCode"/></N403>
          <N404><xsl:value-of select="shipTo/country"/></N404>
        </x12:N4>
      </x12:N1Loop1>

      <!-- N1Loop1 — Bill To (BT) -->
      <x12:N1Loop1>
        <x12:N1>
          <N101>BT</N101>
          <N102><xsl:value-of select="billTo/name"/></N102>
        </x12:N1>
        <x12:N3>
          <N301><xsl:value-of select="billTo/line1"/></N301>
          <xsl:if test="billTo/line2 and normalize-space(billTo/line2) != ''">
            <N302><xsl:value-of select="billTo/line2"/></N302>
          </xsl:if>
        </x12:N3>
        <x12:N4>
          <N401><xsl:value-of select="billTo/city"/></N401>
          <N402><xsl:value-of select="billTo/state"/></N402>
          <N403><xsl:value-of select="billTo/postalCode"/></N403>
          <N404><xsl:value-of select="billTo/country"/></N404>
        </x12:N4>
      </x12:N1Loop1>

      <!-- PO1Loop1 — one per canonical line -->
      <xsl:for-each select="lines">
        <x12:PO1Loop1>
          <x12:PO1>
            <PO101><xsl:value-of select="lineNumber"/></PO101>
            <PO102><xsl:value-of select="quantity"/></PO102>
            <PO103><xsl:value-of select="uom"/></PO103>
            <PO104><xsl:value-of select="unitPrice"/></PO104>
            <PO106>BP</PO106>
            <PO107><xsl:value-of select="sku"/></PO107>
          </x12:PO1>
          <!-- PIDLoop1 / PID_2 — free-form item description (F). Omit if none. -->
          <xsl:if test="description and normalize-space(description) != ''">
            <x12:PIDLoop1>
              <x12:PID_2>
                <PID01>F</PID01>
                <PID05><xsl:value-of select="description"/></PID05>
              </x12:PID_2>
            </x12:PIDLoop1>
          </xsl:if>
        </x12:PO1Loop1>
      </xsl:for-each>

      <!-- CTTLoop1 / CTT — line-item count + quantity hash total -->
      <x12:CTTLoop1>
        <x12:CTT>
          <CTT01><xsl:value-of select="count(lines)"/></CTT01>
          <CTT02><xsl:value-of select="sum(lines/quantity)"/></CTT02>
        </x12:CTT>
      </x12:CTTLoop1>

      <!-- SE — inline (local) segment => NO namespace. Placeholders; X12 Encode
           recomputes SE01, agreement assigns SE02. -->
      <SE>
        <SE01>1</SE01>
        <SE02>0001</SE02>
      </SE>

    </x12:X12_00603_850>
  </xsl:template>

</xsl:stylesheet>
